package chat;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import javax.swing.JOptionPane;
import login.Login;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPesanUtama = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfPilihUser = new javax.swing.JTextField();
        jlStatusPilih = new javax.swing.JLabel();
        jbPilihUser = new javax.swing.JButton();
        tfPesan = new javax.swing.JTextField();
        jbKirimPesan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlUser = new javax.swing.JLabel();
        jbKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        taPesanUtama.setEditable(false);
        taPesanUtama.setColumns(20);
        taPesanUtama.setRows(5);
        taPesanUtama.setText("Menunggu User...");
        jScrollPane1.setViewportView(taPesanUtama);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );

        jLabel1.setText("Pilih User");

        tfPilihUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPilihUserActionPerformed(evt);
            }
        });

        jlStatusPilih.setText("....");

        jbPilihUser.setText("Pilih");
        jbPilihUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPilihUserActionPerformed(evt);
            }
        });

        jbKirimPesan.setText("Kirim");
        jbKirimPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKirimPesanActionPerformed(evt);
            }
        });

        jLabel2.setText("Hello, ");

        jlUser.setText("....");

        jbKeluar.setText("Keluar");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfPesan)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPilihUser)
                    .addComponent(jbPilihUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbKirimPesan, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlStatusPilih)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPilihUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlStatusPilih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPilihUser))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbKirimPesan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jlUser))
                    .addComponent(jbKeluar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPilihUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPilihUserActionPerformed

    }//GEN-LAST:event_tfPilihUserActionPerformed

    private void jbPilihUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPilihUserActionPerformed
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM login WHERE username='" + tfPilihUser.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()){
                jlStatusPilih.setText("User Terpilih");
                                           
                taPesanUtama.setText("Tulis Pesan Kepada " + tfPilihUser.getText()+"\n");
                
            }else{
                jlStatusPilih.setText("User Tidak ada");
                tfPilihUser.setText("");
            }
        }catch(SQLException e){
            System.out.println("error");
        }
        
        PreparedStatement p = null;
        ResultSet rs = null;
        
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "select `id`,`pesan`,`pengirim` from pesan";
            p = c.prepareStatement(sql);
            rs = p.executeQuery();
  
            while (rs.next()) {
 
                Time id;
                id = rs.getTime("id");
                String pengirim = rs.getString("pengirim");
                String pesan = rs.getString("pesan");

                taPesanUtama.append(id +" ("+pengirim+")" +" : " + pesan+"\n");
            }
        }catch (SQLException e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jbPilihUserActionPerformed

    private void jbKirimPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKirimPesanActionPerformed
        String pengirim = jlUser.getText();
        String penerima = tfPilihUser.getText();
        String pesan;
        pesan = tfPesan.getText();
        
        try{
            Connection c = Koneksi.getKoneksi();
            String sql = "INSERT INTO pesan(pengirim, penerima, pesan) VALUES (?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, pengirim);
                p.setString(2, penerima);
                p.setString(3, pesan);
                p.executeUpdate();
                p.close();
        }catch(SQLException e){
            System.out.println("Error");
        }finally{
            tfPesan.setText("");
        }
        
        PreparedStatement p = null;
        ResultSet rs = null;
        
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "select `id`,`pesan`,`pengirim` from pesan ORDER BY id DESC LIMIT 1";
            p = c.prepareStatement(sql);
            rs = p.executeQuery();
            
            if (rs.next()){
                Time id;
                id = rs.getTime("id");
                String sender = rs.getString("pengirim");
                String msg = rs.getString("pesan");

                taPesanUtama.append(id +" ("+sender+")" +" : " + msg+"\n");
            }

        }catch (SQLException e) {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jbKirimPesanActionPerformed

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this,"Apakah anda akan keluar dari sistem ?" , "Informasi", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
           dispose();
          Login log=new Login();
          log.setVisible(true);
        }  
    }//GEN-LAST:event_jbKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JButton jbKirimPesan;
    private javax.swing.JButton jbPilihUser;
    private javax.swing.JLabel jlStatusPilih;
    public javax.swing.JLabel jlUser;
    private javax.swing.JTextArea taPesanUtama;
    private javax.swing.JTextField tfPesan;
    private javax.swing.JTextField tfPilihUser;
    // End of variables declaration//GEN-END:variables
}
